version: 2

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - bodyclose
    - noctx
    - unparam
    - wastedassign
    - misspell
    - gosec
    - mnd
    - gocyclo
    - copyloopvar
    - durationcheck

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0