version: "3.8"

services:
  auth-db:
    image: postgres:latest
    container_name: auth-db
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_user -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  users-db:
    image: postgres:latest
    container_name: users-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user_pass
      POSTGRES_DB: users_db
    ports:
      - "5433:5432"
    volumes:
      - users_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d users_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: .
      dockerfile: Auth-service/Dockerfile
    ports:
      - "50051:50051"
    environment:
      DB_HOST: auth-db
      DB_PORT: 5432
      DB_USER: auth_user
      DB_PASSWORD: auth_pass
      DB_NAME: auth_db

      DB_HOST_USERS: users-db
      DB_PORT_USERS: 5432
      DB_USER_USERS: user
      DB_PASSWORD_USERS: user_pass
      DB_NAME_USERS: users_db
      JWT_SECRET: secret_key
      SERVER_PORT_AUTH: 50051
      ACCESS_TOKEN_DURATION: 900
      REFRESH_TOKEN_DURATION: 86400
    depends_on:
      users-db:
        condition: service_healthy

  chat-service:
    build:
      context: .
      dockerfile: Chat-service/Dockerfile
    ports:
      - "50052:50052"
    environment:
      SERVER_PORT_CHAT: 50052
      AUTH_SERVICE_ADDR: auth-service:50051
      NATS_URL: nats://nats:4222

      DB_HOST: auth-db
      DB_PORT: 5432
      DB_USER: auth_user
      DB_PASSWORD: auth_pass
      DB_NAME: auth_db

      DB_HOST_USERS: users-db
      DB_PORT_USERS: 5432
      DB_USER_USERS: user
      DB_PASSWORD_USERS: user_pass
      DB_NAME_USERS: users_db
    depends_on:
      auth-db:
        condition: service_healthy
      users-db:
        condition: service_healthy
      auth-service:
        condition: service_started
      nats:
        condition: service_started

  notification-service:
    build:
      context: .
      dockerfile: Notification-service/Dockerfile
    container_name: notification-service
    depends_on:
      - nats
    environment:
      AUTH_SERVICE_ADDR: auth-service:50051
      NATS_URL: nats://nats:4222
      
  nats:
    image: nats:latest
    ports:
      - "4222:4222"

  chat-cli:
    build:
      context: .
      dockerfile: chat-cli/Dockerfile
    depends_on:
      - chat-service
    network_mode: host

volumes:
  auth_db_data:
  users_db_data:
